name: Artifacts Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create a file
      run: echo "This is a build artifact." > build-output.txt

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: build-output.txt

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: build-output

    - name: Display artifact
      run: cat build-output.txt
