name: CI Workflow with Simulated 10-Second Timeout

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Simulate a long-running task with a 10-second timeout
    - name: Simulate task with 10-second timeout
      run: |
        echo "Starting task with 10-second timeout..."
        timeout 10s sleep 30    # Sleep for 30 seconds but timeout after 10 seconds
        echo "Task completed (or killed)."
      timeout-minutes: 1        # This is the shortest possible job-level timeout
