name: CI Workflow with Concurrency

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}    # Unique concurrency group for each workflow and branch
  cancel-in-progress: true                           # Automatically cancel any in-progress run of the same group

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Simulate a long-running process
    - name: Simulate long-running task
      run: |
        echo "Starting long-running task..."
        sleep 60  # Simulates a task that takes 60 seconds to complete
        echo "Task completed."
