name: CI Workflow with Continue on Error

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step that is allowed to fail without stopping the workflow
    - name: This step may fail but workflow continues
      run: |
        echo "This step is expected to fail..."
        exit 1   # Forces the step to fail
      continue-on-error: true   # The workflow will continue even if this step fails

    # Another step that runs after the failure
    - name: Final step after failure
      run: echo "This runs even if the previous step failed."
