name: CI Workflow with Matrix (Continue on Error)

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]   # Different OSes
        python-version: [3.8, 3.9, 3.10, 3.11]             # Different Python versions

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
      continue-on-error: true   # The workflow will continue even if this step fails


    # Simulate test that may fail but continue
    - name: Run tests
      run: |
        echo "Running tests on OS: ${{ matrix.os }} with Python version: ${{ matrix.python-version }}"
        if [ "${{ matrix.python-version }}" = "3.8" ] && [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          echo "Simulated test failure"
          exit 1  # Simulating a test failure for Python 3.8 on Ubuntu
        else
          echo "All tests passed."
        fi
      continue-on-error: true   # Continue even if this step fails

    # Final step
    - name: Final step after possible failures
      run: echo "This step runs regardless of test results."
