name: Reusable Workflow

on:
  workflow_call:
    inputs:
      example-input:
        description: 'An example input for the reusable workflow'
        required: false
        type: string
        default: 'default-value'

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Print input
      run: echo "The input value is: ${{ inputs.example-input }}"

    - name: Run a task
      run: echo "Running a reusable task..."
