name: Reusable Workflow

on:
  workflow_call:   # Allows this workflow to be called from other workflows
    # No inputs are defined

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Print a message
      run: echo "This is a reusable workflow."
